
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-10
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"pv-11-course-database-table","number":16,"title":"Add Course database table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/16"},{"author":{"id":"MDQ6VXNlcjcyODQwNDQz","is_bot":false,"login":"rranu","name":"Rajvir Ranu"},"headRefName":"rr-1-correctlink","number":15,"title":"Corrected link to Professor de Vries' About Page","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/15"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"jw-3-modal-capitalization","number":14,"title":"Use title case for Buy/Sell button in modal","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/14"}]
