
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-10
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"al-41-put-students","number":67,"title":"PUT endpoint for Student","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/67"},{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"al-39-post-students","number":66,"title":"POST Endpoint for Student","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/66"},{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"pv-11-course-database-table","number":65,"title":"Add all CRUD endpoints for Courses table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/65"},{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"al-37-get-students","number":64,"title":"GET endpoints added for Students","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/64"},{"author":{"id":"MDQ6VXNlcjU0NTQ2OTYx","is_bot":false,"login":"gargAneesh","name":"Aneesh"},"headRefName":"webIntTestBuySell","number":63,"title":"added web integration tests for buying and selling cows","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/63"}]
