
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-10
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-10
pull_requests: [{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"jw-45-studentplaceholder","number":49,"title":"Create placeholder pages for Student table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/49"},{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"pv-34-courses-controller","number":47,"title":"Create course controller with get all endpoint and tests ","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/47"},{"author":{"id":"MDQ6VXNlcjI1MzQwNzk1","is_bot":false,"login":"AjayLiu","name":"AjayLiu"},"headRefName":"al-31-students-entity-and-migration","number":33,"title":"Add Student.java entity file and Student.json migration file","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/33"},{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"pv-30-course-entity-file","number":32,"title":"Add Entity, Repository and Migration for Course table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/32"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"jw-7-wealth-sorting","number":19,"title":"Fix bug with wealth sorting mishandling commas","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/19"},{"author":{"id":"U_kgDOBtnxJw","is_bot":false,"login":"DderrickLee","name":""},"headRefName":"4-DL-FixProfitTableWidth","number":18,"title":"fixed ProfitTable so that it doesn't have any whitespace","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/18"}]
