
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-10
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"pv-56-course-e2e-fields","number":60,"title":"Test all form fields in Create Commons end-to-end test","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/60"},{"author":{"id":"U_kgDOBtxmHw","is_bot":false,"login":"justinwu13","name":"Justin Wu"},"headRefName":"jw-57-webinttests","number":58,"title":"Add additional web integration test for other Commons functions","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/58"},{"author":{"id":"MDQ6VXNlcjcyODQwNDQz","is_bot":false,"login":"rranu","name":"Rajvir Ranu"},"headRefName":"rr-46-coursesplaceholders","number":54,"title":"Create Placeholder Pages for Courses table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/54"},{"author":{"id":"MDQ6VXNlcjMzNzMyMzky","is_bot":false,"login":"r0ckwav3","name":"Peter"},"headRefName":"pv-34-courses-controller","number":47,"title":"Create course controller with get all endpoint and tests ","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/47"},{"author":{"id":"U_kgDOBtnxJw","is_bot":false,"login":"DderrickLee","name":""},"headRefName":"4-DL-FixProfitTableWidth","number":18,"title":"fixed ProfitTable so that it doesn't have any whitespace","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-10/pull/18"}]
